In [96]:
import yfinance as yf
from datetime import date
import plotly.express as px

import pandas as pd
pd.options.plotting.backend = "plotly"

from DT_BCB_series import CarregaSerieBCB

In [97]:

data_inicial = '02/01/2018'
data_final   = '25/03/2026'

In [98]:
ibov = yf.download('^BVSP', 
                   start=pd.to_datetime(data_inicial, dayfirst=True), 
                   end=pd.to_datetime(data_final, dayfirst=True), 
                   auto_adjust=True)['Close']
if isinstance(ibov.columns, pd.MultiIndex):
    ibov.columns = ibov.columns.get_level_values(0)
ibov.columns = ["Ibov"]
ibov.index.name = "data"
ibov

[*********************100%***********************]  1 of 1 completed

                Ibov
data
2018-01-02   77891.0
2018-01-03   77995.0
2018-01-04   78647.0
2018-01-05   79071.0
2018-01-08   79379.0
...              ...
2026-03-18  179640.0
2026-03-19  180271.0
2026-03-20  176219.0
2026-03-23  181932.0
2026-03-24  182509.0

[2043 rows x 1 columns]

In [99]:
dolar_ptax = CarregaSerieBCB(data_inicial, data_final, 1)
dolar_ptax.index = dolar_ptax.data
dolar_ptax = dolar_ptax.drop(columns='data')
dolar_ptax.columns = ['ptax']

dolar_ptax

Carregando série 1 de 02/01/2018 até 25/03/2026...
URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.1/dados?formato=csv&dataInicial=02/01/2018&dataFinal=25/03/2026
✓ Série carregada com sucesso! 2067 registros
Período: 02/01/2018 até 25/03/2026
Último valor: 5.2275

              ptax
data
2018-01-02  3.2697
2018-01-03  3.2535
2018-01-04  3.2318
2018-01-05  3.2409
2018-01-08  3.2357
...            ...
2026-03-19  5.2587
2026-03-20  5.2800
2026-03-23  5.2440
2026-03-24  5.2599
2026-03-25  5.2275

[2067 rows x 1 columns]

In [100]:
df_ibov = pd.concat([ibov, dolar_ptax], axis=1).dropna()
df_ibov['Ibov_dolar'] = df_ibov['Ibov']/df_ibov['ptax']

df_ibov

                Ibov    ptax    Ibov_dolar
data
2018-01-02   77891.0  3.2697  23822.063186
2018-01-03   77995.0  3.2535  23972.644844
2018-01-04   78647.0  3.2318  24335.354911
2018-01-05   79071.0  3.2409  24397.852448
2018-01-08   79379.0  3.2357  24532.249591
...              ...     ...           ...
2026-03-18  179640.0  5.2112  34471.906663
2026-03-19  180271.0  5.2587  34280.525605
2026-03-20  176219.0  5.2800  33374.810606
2026-03-23  181932.0  5.2440  34693.363844
2026-03-24  182509.0  5.2599  34698.188178

[2043 rows x 3 columns]

In [101]:
df_ibov[['Ibov','Ibov_dolar']].plot()

In [102]:
# IPCA
ipca = CarregaSerieBCB(data_inicial, data_final,433)
ipca

Carregando série 433 de 02/01/2018 até 25/03/2026...
URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados?formato=csv&dataInicial=02/01/2018&dataFinal=25/03/2026
✓ Série carregada com sucesso! 98 registros
Período: 01/01/2018 até 01/02/2026
Último valor: 0.7000

         data  valor
0  2018-01-01   0.29
1  2018-02-01   0.32
2  2018-03-01   0.09
3  2018-04-01   0.22
4  2018-05-01   0.40
..        ...    ...
93 2025-10-01   0.09
94 2025-11-01   0.18
95 2025-12-01   0.33
96 2026-01-01   0.33
97 2026-02-01   0.70

[98 rows x 2 columns]

In [103]:
# IPCA
ipca = CarregaSerieBCB(data_inicial, data_final,433)
ipca.index = ipca.data
ipca = ipca.drop(columns='data')
ipca['acumulado'] = (1 + ipca['valor'] / 100).cumprod().shift(1)
ipca.loc[ipca.index[0], 'acumulado'] = 1 # ipca['acumulado'].iloc[0] = 1
ipca.columns = [ 'valor' , 'ipca_acum']
ipca

Carregando série 433 de 02/01/2018 até 25/03/2026...
URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.433/dados?formato=csv&dataInicial=02/01/2018&dataFinal=25/03/2026
✓ Série carregada com sucesso! 98 registros
Período: 01/01/2018 até 01/02/2026
Último valor: 0.7000

            valor  ipca_acum
data
2018-01-01   0.29   1.000000
2018-02-01   0.32   1.002900
2018-03-01   0.09   1.006109
2018-04-01   0.22   1.007015
2018-05-01   0.40   1.009230
...           ...        ...
2025-10-01   0.09   1.496814
2025-11-01   0.18   1.498161
2025-12-01   0.33   1.500858
2026-01-01   0.33   1.505811
2026-02-01   0.70   1.510780

[98 rows x 2 columns]

In [104]:
# IGPDI
igpdi = CarregaSerieBCB(data_inicial, data_final,190)
igpdi.index = igpdi.data
igpdi = igpdi.drop(columns='data')
igpdi['acumulado'] = (1 + igpdi['valor'] / 100).cumprod().shift(1)
igpdi.loc[igpdi.index[0], 'acumulado'] = 1    # igpdi['acumulado'].iloc[0] = 1
igpdi.columns = [ 'valor' , 'igp_acum']
igpdi

Carregando série 190 de 02/01/2018 até 25/03/2026...
URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.190/dados?formato=csv&dataInicial=02/01/2018&dataFinal=25/03/2026
✓ Série carregada com sucesso! 98 registros
Período: 01/01/2018 até 01/02/2026
Último valor: -0.8400

            valor  igp_acum
data
2018-01-01   0.58  1.000000
2018-02-01   0.15  1.005800
2018-03-01   0.56  1.007309
2018-04-01   0.93  1.012950
2018-05-01   1.64  1.022370
...           ...       ...
2025-10-01  -0.03  1.790864
2025-11-01   0.01  1.790327
2025-12-01   0.10  1.790506
2026-01-01   0.20  1.792296
2026-02-01  -0.84  1.795881

[98 rows x 2 columns]

In [105]:
inflacao  = pd.merge( ipca.ipca_acum , igpdi.igp_acum , on='data' )
inflacao

            ipca_acum  igp_acum
data
2018-01-01   1.000000  1.000000
2018-02-01   1.002900  1.005800
2018-03-01   1.006109  1.007309
2018-04-01   1.007015  1.012950
2018-05-01   1.009230  1.022370
...               ...       ...
2025-10-01   1.496814  1.790864
2025-11-01   1.498161  1.790327
2025-12-01   1.500858  1.790506
2026-01-01   1.505811  1.792296
2026-02-01   1.510780  1.795881

[98 rows x 2 columns]

In [106]:
inflacao.plot()

In [107]:
df_ibov = pd.merge(df_ibov , inflacao , on = 'data' , how ='outer')
df_ibov=df_ibov.ffill()
df_ibov

                Ibov    ptax    Ibov_dolar  ipca_acum  igp_acum
data
2018-01-01       NaN     NaN           NaN    1.00000  1.000000
2018-01-02   77891.0  3.2697  23822.063186    1.00000  1.000000
2018-01-03   77995.0  3.2535  23972.644844    1.00000  1.000000
2018-01-04   78647.0  3.2318  24335.354911    1.00000  1.000000
2018-01-05   79071.0  3.2409  24397.852448    1.00000  1.000000
...              ...     ...           ...        ...       ...
2026-03-18  179640.0  5.2112  34471.906663    1.51078  1.795881
2026-03-19  180271.0  5.2587  34280.525605    1.51078  1.795881
2026-03-20  176219.0  5.2800  33374.810606    1.51078  1.795881
2026-03-23  181932.0  5.2440  34693.363844    1.51078  1.795881
2026-03-24  182509.0  5.2599  34698.188178    1.51078  1.795881

[2085 rows x 5 columns]

In [108]:

df_ibov['ibov_defla_ipca'] = df_ibov['Ibov'] / df_ibov['ipca_acum']
df_ibov['ibov_defla_igpd'] = df_ibov['Ibov'] / df_ibov['igp_acum']


df_ibov = df_ibov.dropna()
df_ibov

,Ibov,ptax,Ibov_dolar,ipca_acum,igp_acum,ibov_defla_ipca,ibov_defla_igpd
data,,,,,,,
2018-01-02,77891.0,3.2697,23822.063186,1.00000,1.000000,77891.000000,77891.000000
2018-01-03,77995.0,3.2535,23972.644844,1.00000,1.000000,77995.000000,77995.000000
2018-01-04,78647.0,3.2318,24335.354911,1.00000,1.000000,78647.000000,78647.000000
2018-01-05,79071.0,3.2409,24397.852448,1.00000,1.000000,79071.000000,79071.000000
2018-01-08,79379.0,3.2357,24532.249591,1.00000,1.000000,79379.000000,79379.000000
...,...,...,...,...,...,...,...
2026-03-18,179640.0,5.2112,34471.906663,1.51078,1.795881,118905.470822,100028.917462
2026-03-19,180271.0,5.2587,34280.525605,1.51078,1.795881,119323.135886,100380.277108
2026-03-20,176219.0,5.2800,33374.810606,1.51078,1.795881,116641.077504,98124.002484
2026-03-23,181932.0,5.2440,34693.363844,1.51078,1.795881,120422.568011,101305.171519
2026-03-24,182509.0,5.2599,34698.188178,1.51078,1.795881,120804.489948,101626.462353

In [110]:
df_ibov[['Ibov','Ibov_dolar','ibov_defla_ipca','ibov_defla_igpd']].plot()

In [111]:
cdi = CarregaSerieBCB(data_inicial,data_final,12)
cdi.index = cdi.data
cdi = cdi.drop(columns='data')
cdi.columns = ['cdi_dia']
cdi['acumulado'] = (1 + cdi['cdi_dia'] / 100).cumprod().shift(1)
cdi.loc[cdi.index[0], 'acumulado']
cdi

Carregando série 12 de 02/01/2018 até 25/03/2026...
URL: https://api.bcb.gov.br/dados/serie/bcdata.sgs.12/dados?formato=csv&dataInicial=02/01/2018&dataFinal=25/03/2026
✓ Série carregada com sucesso! 2067 registros
Período: 02/01/2018 até 25/03/2026
Último valor: 0.0543

             cdi_dia  acumulado
data
2018-01-02  0.026444        NaN
2018-01-03  0.026444   1.000264
2018-01-04  0.026444   1.000529
2018-01-05  0.026444   1.000794
2018-01-08  0.026444   1.001058
...              ...        ...
2026-03-19  0.054266   2.005248
2026-03-20  0.054266   2.006336
2026-03-23  0.054266   2.007424
2026-03-24  0.054266   2.008514
2026-03-25  0.054266   2.009604

[2067 rows x 2 columns]

In [112]:

df_ibov_cdi = pd.concat([ibov / ibov.iloc[0], cdi['acumulado']], axis=1).dropna()

In [113]:
df_ibov_cdi

                Ibov  acumulado
data
2018-01-03  1.001335   1.000264
2018-01-04  1.009706   1.000529
2018-01-05  1.015149   1.000794
2018-01-08  1.019104   1.001058
2018-01-09  1.012492   1.001323
...              ...        ...
2026-03-18  2.306300   2.004143
2026-03-19  2.314401   2.005248
2026-03-20  2.262379   2.006336
2026-03-23  2.335726   2.007424
2026-03-24  2.343133   2.008514

[2042 rows x 2 columns]

In [114]:
df_ibov_cdi.plot()